on:
  push:
  pull_request:

name: Test and Lint

jobs:
  test:
    name: Test and Lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run tests and lint
        id: test-and-lint
        run: |
          npm install
          npm test
          npm run tslint
