on:
  push:
  pull_request:

name: Test and Lint

jobs:
  test:
    name: Test and Lint
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: ['20', '22']

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Run tests and lint
        id: test-and-lint
        run: |
          npm install
          cd docs
          npm install
          cd ..
          npm test
          npm run eslint
